# vim: ft=bash

# load helper
. "${_ENV_CONFIG_DIR:-$HOME/.config/dotfiles}/helper" || echo "ERROR: unable to load helper, environment setup may fail!"

_env_debug "bash_profile"
_env_source "$_ENV_CONFIG_DIR/common_profile"

# unload helper
_env_run_after
_env_cleanup

[[ $- != *i* ]] && return
. ~/.bashrc
