# vim: ft=bash

# load helper
. "${_ENV_CONFIG_DIR:-$HOME/.config/dotfiles}/helper" || echo "ERROR: unable to load helper, environment setup may fail!"

_env_debug "bashrc"

for file in aliases functions; do
    _env_source "$_ENV_CONFIG_DIR/$file"
done
unset file


HISTCONTROL="ignoredups:erasedups"
HISTSIZE=1000
HISTFILESIZE=10000
HISTTIMEFORMAT="%h %d %H:%M:%S "

# append session history to history file upon exit
shopt -s histappend
# save multiline commands as multiline but in one history entry
shopt -s cmdhist
shopt -s lithist
# auto edit mistakes in path
shopt -s cdspell
# show command from history instead running !! !34
shopt -s histverify
# do not accept output replacing existing file >| to force
set -o noclobber
# return error if any of the commands in pipe chain exit > 0
#set -o pipefail


_env_cleanup_add _ENV_BASH_DIR
_ENV_BASH_DIR="$_ENV_CONFIG_DIR/bash"

for file in functions ps completions; do
    _env_source "$_ENV_BASH_DIR/$file"
done
unset file

_env_source "$_ENV_CONFIG_DIR/${_ENV_OS}_rc"
_env_debug "utils"
_env_source "$_ENV_CONFIG_DIR/utils"/*

# unload helper
_env_run_after
_env_cleanup

