# vim: ft=zsh

# load helper
. "${_ENV_CONFIG_DIR:-$HOME/.config/dotfiles}/helper" || echo "ERROR: unable to load helper, environment setup may fail!"

_env_debug "zprofile"
_env_source "$_ENV_CONFIG_DIR/common_profile"

# word splitting (POSIX)
setopt sh_word_split

# unload helper
_env_run_after
_env_cleanup
