# vim: ft=zsh

# load helper
. "${_ENV_CONFIG_DIR:-$HOME/.config/dotfiles}/helper" || echo "ERROR: unable to load helper, environment setup may fail!"

_env_debug "zshrc"

for file in aliases functions; do
    _env_source "$_ENV_CONFIG_DIR/$file"
done
unset file

# word splitting (POSIX)
setopt sh_word_split
# case-unsensitive-globbing
setopt no_case_glob
# cd if cd is missed
setopt auto_cd
setopt cd_silent
# auto corrections
setopt correct
#setopt correct_all
# protect > overwrites
setopt no_clobber
setopt append_create

# emacs key binding
bindkey -e

# home, end
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
# pgup, pgdown
bindkey '^[[5~' history-search-backward
bindkey '^[[6~' history-search-forward
# delete, insert
bindkey '^[[3~' delete-char
bindkey '^[[2~' quoted-insert

# hostory file
HISTSIZE=1000
SAVEHIST=10000
setopt extended_history
setopt append_history
setopt inc_append_history_time
# don't save dups to file
setopt hist_save_no_dups
# don't save history command itself
setopt hist_no_store

# session history
# omit commands started with space
setopt hist_ignore_space
# ingnore dups one after another
setopt hist_ignore_dups
# ignore dups in session history
#setopt hist_ignore_all_dups
# don't search dups
setopt hist_find_no_dups
# show command from history instead running !!
setopt hist_verify

_env_cleanup_add _ENV_ZSH_DIR
_ENV_ZSH_DIR="$_ENV_CONFIG_DIR/zsh"

for file in functions ps completions; do
    _env_source "$_ENV_ZSH_DIR/$file"
done
unset file

## plugins
# autosuggestions
_env_source "$HOMEBREW_PREFIX"/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# syntax highlight
_env_source "$HOMEBREW_PREFIX"/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

_env_source "$_ENV_CONFIG_DIR/${_ENV_OS}_rc"
_env_debug "setup utils"
_env_source "$_ENV_CONFIG_DIR"/utils/*(.N)

# unload helper
_env_run_after
_env_cleanup

