" Use Vim defaults instead of 100% vi compatibility
set nocompatible

" runtime config
set runtimepath^=~/.config/vim
set packpath+=~/.config/vim

" imports
runtime! core.vim

if has('eval')
    runtime! plug.vim
    runtime! functions.vim
endif

runtime! ui.vim

"if has('syntax')
    runtime! formatting.vim
"endif

runtime! mappings.vim
