" Use Vim defaults instead of 100% vi compatibility
set nocompatible        
 
" runtime config
set runtimepath^=~/.config/vim
set packpath+=~/.config/vim

" imports
runtime! core.vim
runtime! plug.vim
runtime! functions.vim
runtime! ui.vim
runtime! formatting.vim
runtime! mappings.vim

