[mgr]
ratio = [1,3,4]
show_symlink = true

[preview]
wrap = "yes"
tab_size = 2
image_delay = 100

[tasks]
image_bound = [0,0]

[[plugin.prepend_previewers]]
name = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
