# vim: filetype=zsh

# word splitting (POSIX)
setopt sh_word_split
# case-unsensitive-globbing
setopt no_case_glob
# cd if cd is missed
setopt auto_cd
setopt cd_silent
# auto corrections
setopt correct
setopt correct_all
# protect > overwrites
setopt no_clobber
setopt append_create

# emacs key binding
bindkey -e

# home, end
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
# pgup, pgdown
bindkey '^[[5~' history-search-backward
bindkey '^[[6~' history-search-forward
# delete, insert
bindkey '^[[3~' delete-char
bindkey '^[[2~' quoted-insert

# history
alias hi='history -i 50'
## file
HISTSIZE=1000
SAVEHIST=10000
setopt extended_history
setopt append_history
setopt inc_append_history_time
# don't save dups to file
setopt hist_save_no_dups
# don't save history command itself
setopt hist_no_store

## session
# omit commands started with space
setopt hist_ignore_space
# ingnore dups one after another
setopt hist_ignore_dups
# ignore dups in session history
#setopt hist_ignore_all_dups
# don't search dups
setopt hist_find_no_dups
# show command from history instead running !!
setopt hist_verify

zsh_home="${_ENV_CONFIG_DIR:-"$HOME/.config"}/zsh"
for file in alias ps completions functions; do
    _env_source "$zsh_home/$file" "$file_$_ENV_OS"
done
unset zsh_home file

## plugins
# autosuggestions
_env_source "$HOMEBREW_PREFIX"/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# syntax highlight
_env_source "$HOMEBREW_PREFIX"/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

