export HISTCONTROL="ignoredups"
export HISTSIZE=1000
export HISTFILESIZE=10000
export HISTTIMEFORMAT="%h %d %H:%M:%S "

# append session history to history file upon exit
shopt -s histappend
# save multiline commands as multiline but in one history entry
shopt -s cmdhist
shopt -s lithist
# auto edit mistakes in path
shopt -s cdspell
# show command from history instead running !! !34
shopt -s histverify
# do not accept output replacing existing file >| to force
set -o noclobber
# return error if any of the commands in pipe chain exit > 0
#set -o pipefail

bash_home="${DOTFILES:-"$HOME/.config"}/bash"

# ps
[ -f "$bash_home/ps" ] && . "$bash_home/ps"
[ -f "$bash_home/ps_$DOTFILES_OS" ] && . "$bash_home/ps_$DOTFILES_OS"

# completions
[ -f "$bash_home/completions_$DOTFILES_OS" ] && . "$bash_home/completions_$DOTFILES_OS"
[ -f "$bash_home/completions" ] && . "$bash_home/completions"

# functions
[ -f "$bash_home/functions" ] && . "$bash_home/functions"
[ -f "$bash_home/functions_$DOTFILES_OS" ] && . "$bash_home/functions_$DOTFILES_OS"

unset bash_home

