export HISTCONTROL="ignoredups:erasedups"
export HISTSIZE=1000
export HISTFILESIZE=10000
export HISTTIMEFORMAT="%h %d %H:%M:%S "

# append session history to history file upon exit
shopt -s histappend
# save multiline commands as multiline but in one history entry
shopt -s cmdhist
shopt -s lithist
# auto edit mistakes in path
shopt -s cdspell
# show command from history instead running !! !34
shopt -s histverify
# do not accept output replacing existing file >| to force
set -o noclobber
# return error if any of the commands in pipe chain exit > 0
#set -o pipefail

bash_home="${_ENV_CONFIG_DIR:-"$HOME/.config"}/bash"

# ps
for file in ps completions functions; do
    _env_source "$bash_home/$file" "$file_$_ENV_OS"
done

unset bash_home file

